name: waterflow_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  get: ^4.6.6
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_images/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app_images/WaterFlow_Logo.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/app_images/WaterFlow_Logo.png"

  ios: true
  remove_alpha_ios: true

  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_images/WaterFlow_Logo.png"